### PR TITLE
Add more logging around verification and storage

### LINKED ISSUE #13: Add more logging to the verification process
That will make future debugging much easier.

### PR DESCRIPTION
**Pull request by katszwn**
Fixes #13 

Makes the whole process visible, makes it easy to determine which point of the process did not succeed.

### CODE REVIEW

**Comment by Exulansis** [comment]
Looks good, we could hook the logging up to some env variable or other way of signalling we're in dev mode. So we can enable or disable it without changing the source code.

**Comment by Exulansis** [comment]
Might be overkill for now though.

**Comment by katszwn** [comment]
@Exulansis I like the idea, but I think more useful for now would be to hook up some error reporting software - like Sentry or Raygun. Will look into it :)

**Comment by Exulansis** [comment]
We should discuss sentry when I get back, given that it anonymizes reports well, we should definitely use it.

**Pull request merged**
